[package]
name = "element_idle"
version = "0.1.0"
edition = "2024"

[dependencies]
chrono = "0.4.42"
ggegui = "0.4.0"
ggez = "0.9.3"
rust_decimal = { version = "1.39.0", features = ["macros", "maths"] }
